// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-enquiries.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.1";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var notAuthenticated = {
  content: [{ type: "text", text: "Not authenticated." }],
  isError: true
};

// src/lib/mcp/tools/list-enquiries.ts
var list_enquiries_default = defineTool({
  name: "list_enquiries",
  title: "List enquiries",
  description: "List client enquiries submitted through the Magizhchi Moments contact form, newest first. Requires an admin account.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Maximum number of enquiries to return (default 20)."),
    status: z.string().optional().describe("Filter by enquiry status, e.g. 'New'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    let query = supabaseForUser(ctx).from("enquiries").select("id, name, email, phone, event_type, event_date, message, status, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { enquiries: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/update-enquiry-status.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^3.25.76";
var update_enquiry_status_default = defineTool2({
  name: "update_enquiry_status",
  title: "Update enquiry status",
  description: "Update the status of a single enquiry, for example to 'New', 'Contacted', 'Booked', or 'Closed'. Requires an admin account.",
  inputSchema: {
    id: z2.string().describe("The enquiry id."),
    status: z2.string().trim().min(1).describe("The new status value.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, status }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const { data, error } = await supabaseForUser(ctx).from("enquiries").update({ status }).eq("id", id).select("id, name, status").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return {
        content: [{ type: "text", text: "No enquiry was updated \u2014 check the id and your permissions." }],
        isError: true
      };
    return {
      content: [{ type: "text", text: `Enquiry ${data.id} (${data.name}) is now "${data.status}".` }],
      structuredContent: { enquiry: data }
    };
  }
});

// src/lib/mcp/tools/enquiry-summary.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
var enquiry_summary_default = defineTool3({
  name: "enquiry_summary",
  title: "Enquiry summary",
  description: "Summarise all enquiries by status and event type, with the date of the most recent enquiry. Requires an admin account.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const { data, error } = await supabaseForUser(ctx).from("enquiries").select("status, event_type, created_at").order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const byStatus = {};
    const byEventType = {};
    for (const row of rows) {
      const status = row.status ?? "Unknown";
      const eventType = row.event_type ?? "Unspecified";
      byStatus[status] = (byStatus[status] ?? 0) + 1;
      byEventType[eventType] = (byEventType[eventType] ?? 0) + 1;
    }
    const summary = {
      total: rows.length,
      byStatus,
      byEventType,
      latestEnquiryAt: rows[0]?.created_at ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jwnvpqwcjffazvibvsak";
var mcp_default = defineMcp({
  name: "magizhchi-moments-mcp",
  title: "Magizhchi Moments",
  version: "0.1.0",
  instructions: "Tools for the Magizhchi Moments event decor studio. Use `list_enquiries` to read client enquiries from the website contact form, `enquiry_summary` for an overview by status and event type, and `update_enquiry_status` to move an enquiry through the pipeline. All tools act as the signed-in admin user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_enquiries_default, enquiry_summary_default, update_enquiry_status_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
